"""create tables

Revision ID: 48ebcde45e11
Revises: None
Create Date: 2013-05-04 12:43:41.246468

"""

# revision identifiers, used by Alembic.
revision = '48ebcde45e11'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('fullname', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('openid', sa.String(length=256), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('receive_email', sa.Boolean(), nullable=True),
    sa.Column('email_alerts', sa.Boolean(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('category', sa.SmallInteger(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_assoc',
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_assoc')
    op.drop_table('content')
    op.drop_table('keywords')
    op.drop_table('user')
    ### end Alembic commands ###
